name: Architectural Decision Record
description: Propose a new architectural decision
title: "[ADR]: "
labels: ["adr"]
body:
  - type: markdown
    attributes:
      value: |
        # Architectural Decision Record
        Use this template to propose a new architectural decision that needs to be documented.

  - type: input
    id: decision-title
    attributes:
      label: Decision Title
      description: A clear and concise title for this architectural decision
      placeholder: "e.g., Use PostgreSQL as the primary database"
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Status
      description: The current status of this architectural decision
      options:
        - Proposed
        - Accepted
        - Rejected
        - Deprecated
        - Superseded
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What is the issue that we're seeing that is motivating this decision or change?
      placeholder: "Describe the context and problem statement..."
    validations:
      required: true

  - type: textarea
    id: decision
    attributes:
      label: Decision
      description: What is the change that we're proposing and/or doing?
      placeholder: "Describe the proposed solution..."
    validations:
      required: true

  - type: textarea
    id: consequences
    attributes:
      label: Consequences
      description: What becomes easier or more difficult to do because of this change?
      placeholder: "List the positive and negative consequences of this decision..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other options were considered? Why weren't they chosen?
      placeholder: "Describe alternative solutions that were considered..."
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any references to support this decision?
      placeholder: "Links to documentation, discussions, or other relevant information..."
    validations:
      required: false
