name: Generate ADR Markdown

on:
  issues:
    types:
      - closed

permissions:
  contents: write

jobs:
  create-adr:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'ADR')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate ADR Markdown
        uses: ./ # Local action in the repository
        with:
          label_name: "ADR"
          destination_folder: "adr-files"
          adr_status: "proposed"
